# Generated by Django 3.2.12 on 2022-03-31 06:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_management_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='feedback',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='tasksubmission',
            name='user_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Instructor', to=settings.AUTH_USER_MODEL),
        ),
    ]
